SELECT 
    CASE 
        WHEN b.GRADE > 7 THEN a.NAME 
        ELSE NULL 
    END AS NAME, 
    b.GRADE, 
    a.MARKS 
FROM STUDENTS a 
JOIN GRADES b 
    ON a.MARKS BETWEEN b.MIN_MARK AND b.MAX_MARK 
ORDER BY b.GRADE DESC, a.NAME ASC;
